# Generated by Django 2.2 on 2022-04-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_blog', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
