# Generated by Django 2.2 on 2022-04-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_blog', '0005_auto_20220423_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_images',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='files/')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_my_blog.Post')),
            ],
        ),
    ]
