# Generated by Django 2.2 on 2022-04-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_blog', '0007_auto_20220424_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
